apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ehlvh6tb5-nodejs 
  janus-idp.io/tekton: ehlvh6tb5-nodejs
  backstage.io/kubernetes-id: ehlvh6tb5-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ehlvh6tb5-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml